version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env.prod
    depends_on:
      - db
    networks:
      - django_network

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    networks:
      - django_network

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    restart: unless-stopped
    volumes:
      - static_volume:/vol/static
      - media_volume:/vol/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - django_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  django_network:
    driver: bridge