# Generated by Django 4.2.2 on 2025-10-13 20:42

import app_ecommerce.models_mixins
import app_ecommerce.validators
import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique identifier')),
                ('num_id', models.IntegerField(editable=False, unique=True, verbose_name='#')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date of updating')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ecommerce.category', verbose_name='parent category')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique identifier')),
                ('num_id', models.IntegerField(editable=False, unique=True, verbose_name='#')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date of updating')),
                ('session_id', models.CharField(max_length=32, verbose_name='session')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[app_ecommerce.validators.phone_number_validator], verbose_name='phone number')),
                ('last_visit', models.DateTimeField(auto_now=True, verbose_name='last visit')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique identifier')),
                ('num_id', models.IntegerField(editable=False, unique=True, verbose_name='#')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date of updating')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/goods_images/', verbose_name='image')),
                ('price', models.IntegerField(verbose_name='price')),
                ('price_prefix', models.BooleanField(default=False, verbose_name='price prefix')),
                ('count', models.IntegerField(verbose_name='count')),
                ('is_available', models.BooleanField(editable=False)),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ecommerce.category', verbose_name='category')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'goods',
                'verbose_name_plural': 'goods',
            },
            bases=(app_ecommerce.models_mixins.CompressImageBeforeSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique identifier')),
                ('num_id', models.IntegerField(editable=False, unique=True, verbose_name='#')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date of updating')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True)),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.IntegerField(verbose_name='price')),
                ('price_prefix', models.BooleanField(default=False, verbose_name='price prefix')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique identifier')),
                ('num_id', models.IntegerField(editable=False, unique=True, verbose_name='#')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date of updating')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('value', models.CharField(max_length=150, verbose_name='value')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('goods', models.ManyToManyField(to='app_ecommerce.goods', verbose_name='goods')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'parameter',
                'verbose_name_plural': 'parameters',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique identifier')),
                ('num_id', models.IntegerField(editable=False, unique=True, verbose_name='#')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date of updating')),
                ('status', models.CharField(choices=[('new', 'не обработанная заявка'), ('active', 'в работе'), ('closed', 'завершено'), ('success_sell', 'услуга оказана')], default='new', max_length=12, verbose_name='status')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ecommerce.customer', verbose_name='customer')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_ecommerce.goods', verbose_name='goods')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_ecommerce.service', verbose_name='service')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique identifier')),
                ('num_id', models.IntegerField(editable=False, unique=True, verbose_name='#')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date of updating')),
                ('text', models.TextField(verbose_name='text')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ecommerce.customer', verbose_name='customer')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique identifier')),
                ('num_id', models.IntegerField(editable=False, unique=True, verbose_name='#')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date of updating')),
                ('num_id_customer_unique', models.IntegerField(editable=False, verbose_name='the customer`s contact #')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
                ('phone_number', models.CharField(max_length=20, validators=[app_ecommerce.validators.phone_number_validator], verbose_name='phone number')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ecommerce.customer', verbose_name='customer')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
